
networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  postgres:
    image: postgres:15.1-alpine
    networks:
      - app
    env_file:
      - .env
    ports:
      - '5437:5432'
    volumes:
      - db-data:/var/lib/postgresql/data